import { apiKey, apiUrl } from "@/config";
import { getToken } from "@/lib/set-localstorage";
import { getTagDetailsResponse, getTagResponse, TagFormData } from "@/types/tag-type";
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"; // Ensure /react is imported

export const tagApi = createApi({
    reducerPath: "tagApi",
    baseQuery: fetchBaseQuery({
        baseUrl: apiUrl,
        prepareHeaders: (headers) => {
            headers.set("x-api-key", apiKey!); // Add API key here
            headers.set("Authorization", `Bearer ${getToken('token')}`); // Add API key here
            return headers;
        },
        credentials: "include",
    }),
    tagTypes: ["tag"],
    endpoints: (builder) => ({
        addNewTag: builder.mutation<void, TagFormData>({
            query: (data) => {
                const formData = new FormData();
                formData.append("data", JSON.stringify(data))
                return {
                    url: "/add-tag",
                    method: "POST",
                    body: formData, // Use formData as body
                };
            },
            invalidatesTags: [{ type: "tag", id: "LIST" }],
        }),
        updateTag: builder.mutation<void, TagFormData>({
            query: (data) => {
                const formData = new FormData();
                formData.append("data", JSON.stringify(data))
                return {
                    url: `edit-tag-details/${data.id}`,
                    method: "PUT",
                    body: formData, // Use formData as body
                };
            },
            invalidatesTags: [{ type: "tag", id: "LIST" }],
        }),
        tagDetails: builder.query<getTagDetailsResponse, { id: string }>({
            query: ({ id }) => ({
                url: `tag-details/${id}`,
                method: "GET",
            }),
            providesTags: [{ type: "tag", id: "LIST" }],
        }),
        deletetag: builder.mutation<void, { id: string }>({
            query: ({ id }) => ({
                url: `tag-remove/${id}`,
                method: "DELETE", // Use DELETE instead of PUT
            }),
            invalidatesTags: [{ type: "tag", id: "LIST" }],
        }),
        getAllTag: builder.query<
            getTagResponse,
            {
                type?: string;
                rowsPerPage?: number;
                page?: number;
            } | void
        >({
            query: (filters) => {
                // Initialize the query params object with the default value for isActive
                const params: Record<string, string | number | boolean> = {
                    // is_active: filters.is_active, // Default to true
                };
                // Add filters to the query parameters if they are present
                if (filters) {
                    // if (filters.type) {
                    //     params.type = filters.type; // Convert number to string
                    // }
                    if (filters.rowsPerPage) {
                        params.rowsPerPage = filters.rowsPerPage; // Convert number to string
                    }
                    if (filters.page) {
                        params.page = filters.page; // Convert number to string
                    }
                }

                return {
                    url: "all-tag",
                    params, // Use the dynamically constructed params
                    method: "GET",
                };
            },
            providesTags: [{ type: "tag", id: "LIST" }],
        }),
    }),
});

// Correct hook name generated by createApi
export const {
    useAddNewTagMutation,
    useGetAllTagQuery,
    useTagDetailsQuery,
    useUpdateTagMutation,
    useDeletetagMutation,
} = tagApi;