import type { Metadata } from "next";
import { AppLayoutShell } from "./app-layout-shell";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <AppLayoutShell>{children}</AppLayoutShell>;
}
